### ISSUE TITLE
Issue with Custom Operations during CoreML conversion and high CPU usage after conversion

### ISSUE THREAD

**Issue by zjkhurry** [huggingface/coreml-examples#10]
I am encountering the following error when converting my model using the original code from the notebook. It seems to be related to Custom Operations. How can I resolve this?

<img width="1096" alt="SCR-20241011-dbrr" src="https://github.com/user-attachments/assets/a43be3b6-653c-4bac-90ee-1597b50b9e04">

Environment:

macOS 15
Python 3.11.8
coremltools 8.0
Torch version 2.4.1

**Comment by rbown25** [comment]
I'm seeing exactly the same problem with macOS 14.7, Python 3.11.10

**Comment by pcuenca** [comment]
Should be fixed by #13! Please, reopen if you still experience problems.

**Comment by rbown25** [comment]
Amazing!  - this now works perfectly. Huge thanks for getting onto this so quickly!
